name: Binary upload action

description: pull a specific docker image

inputs:
  repository:
    description: 'Repository to checkout, defaults to ""'
    default: ''
    type: string
  trigger-event:
    description: "Trigger Event in caller that determines whether or not to upload"
    type: string
    default: ''
env:
  AWS_WEB_IDENTITY_TOKEN_FILE: aws.web.identity.token.file
  AWS_DEFAULT_REGION: us-east-1
  AWS_ROLE_ARN: arn:aws:iam::749337293305:role/gha_workflow_nightly_build_wheels
  
runs:
  using: composite
  steps:
    - name: Configure aws credentials and upload
        shell: bash
        run: |
          set -euxo pipefail

          # shellcheck disable=SC1090
          source "${BUILD_ENV_FILE}"
          
          pip install awscli==1.32.18
          yum install -y jq
          sleep 3 # Need to have a delay to acquire this
          echo "ACTIONS_ID_TOKEN_REQUEST_URL: ${ACTIONS_ID_TOKEN_REQUEST_URL}"
          curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.amazonaws.com" \
            | jq -r '.value' > "${AWS_WEB_IDENTITY_TOKEN_FILE}"
          echo "Helo world" > testfile.txt
          aws s3 cp testfile.txt s3://pytorch/whl/nightly/testfile.txt
            

